config/routes.rb
ChrisderoseCom::Application.routes.draw do
  root "viewhandler#index"

  get '/images/video-thumbnails/:section/:title.jpg', to: 'videos#thumbnail', as: 'video_thumbnail'
  get '/video/:title', to: 'videos#show', as: 'video'
end

app/models/section.rb
class DTIYamlObject
  def initialize yaml
    self.class.yaml_accessors.each{|a| instance_variable_set "@#{a}", yaml[a]}
  end

  class << self
    attr_accessor :yaml_accessors

    def yaml_accessor(*attrs)
      attr_accessor *attrs
      @yaml_accessors = attrs
    end
  end
end

class Link < DTIYamlObject
  yaml_accessor *%w(title description date href image)

  def slug
    @title.parameterize
  end
end

class Section < DTIYamlObject
  yaml_accessor *%w(title klass description href template nav images)
  attr_accessor :links
  
  def initialize section 
    super section
    @template ||= 'landscape'
    @links = section['links'].collect{|link| Link.new link} if section['links']
  end

  def format
    @template
  end

  def slug
    @title.parameterize
  end

  def find_link(slug)
    links.find{|l| l.slug == slug}
  end

  def self.all(page='home')
    config = File.join(Rails.root, 'config', '%s.yml' % page)
    YAML::load_documents(File.open config).collect do |s|
      klass = s['klass'] || 'Section'
      Kernel.const_get(klass).new s
    end
  end

  def self.find_by_slug(slug, page='home')
    all(page).find{|s| s.slug == slug }
  end

  def self.find_by_klass(klass, page='home')
    all(page).find_all{|s| s.klass == klass}
  end
end

class YoutubeSection < Section
  yaml_accessor *%w(title klass description href template nav images channel scrape_since)

  def initialize section
    super section
  end

  def links
    YoutubeVideo.all.collect {|v| Link.new v}
  end
end

app/models/youtube_video.rb
class YoutubeVideo < ActiveRecord::Base
  default_scope :order => "published_at DESC"

  scope :without_captions, -> { where(subtitle: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  caches_page :show, :thumbnail

  def show 
    @sections = Section.all
    @video = YoutubeVideo.find_by_slug params[:title]
    @sidebar_videos = YoutubeVideo.where.not(id: @video.id).offset(rand(YoutubeVideo.count)).first(3)
  end

  def thumbnail
    link = YoutubeVideo.find_by_slug(params[:title]) ||
      Section.find_by_slug(params[:section]).find_link(params[:title])

    yt = Yt::Video.new url: link.href

    thumbnail = link.try(:thumbnail_high) || yt.thumbnail_url(:high)
    begin
      send_file( 
        open(thumbnail),
        :disposition => 'inline',
        :type => 'image/jpeg',
        :x_sendfile => true 
      )
    rescue OpenURI::HTTPError
      thumbnail = 'public/no-yt-thumbnail.jpg'
      retry
    end
  end
end

app/controllers/viewhandler_controller.rb
class ViewhandlerController < ApplicationController
  caches_page :index
  caches_page :video_thumbnail

  def index
    @sections = Section.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def to_paragraphs(string, lines)
    res = ''
    string.each_line('.').each_with_index do |line, index|
      res += (index % lines == 0) ? "</p><p>%s" % [line] : line
    end
    content_tag(:p, res.html_safe)
  end
end

app/helpers/viewhandler_helper.rb
module ViewhandlerHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Chris DeRose", '/', :class => 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.text-capitalize
        -@sections.each do |section|
          - nav_link = section.nav ? section.nav : section.title
          - unless section.links.nil?
            %li
              =link_to nav_link, "/#%s" % [section.slug]
        - end if @sections
        %li
          =link_to "Blog", '#blog'
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to fa_icon("twitter", :class => 'fa-2x'), 'https://www.twitter.com/derose', :target => '_blank'
        %li
          =link_to fa_icon("facebook", :class => 'fa-2x'), 'https://www.facebook.com/chris.derose.16', :target => '_blank'
        %li
          =link_to fa_icon("github", :class => 'fa-2x'), 'https://www.github.com/brighton36', :target => '_blank'
        %li
          =link_to fa_icon("soundcloud", :class => 'fa-2x'), 'https://soundcloud.com/bitcoinuncensored', :target => '_blank'
        %li
          =link_to fa_icon("youtube", :class => 'fa-2x'), 'https://www.youtube.com/user/cderose36', :target => '_blank'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Chris DeRose
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600", :rel => "stylesheet", :type => "text/css"}/
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", :async => Rails.env == "production"
    = csrf_meta_tags
  %body
    = render :partial => 'layouts/nav'
    %header
      #top.container
        .row
          .col-md-4.col-lg-4
            =image_tag 'profile.jpeg', :class => 'profile'
          .col-md-8.col-lg-8.jumbotron.hero-spacer.hidden-sm.hidden-xs
            %p=t('tagline' ).html_safe
    = yield
    %footer.text-muted
      .row
        .col-lg-12.text-center
          =t 'copyright_html', :year => Time.now.year 

    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-648793-7', 'auto');
        ga('send', 'pageview');

app/views/videos/_sidebar.html.haml
%h3 Additional Videos
- @sidebar_videos.each do |link|
  .row
    = link_to image_tag(video_thumbnail_path(:title => link.slug, :section => 'video'), :class => 'lg-thumbnail', :alt => link.title), video_path(:title => link.slug ), :class => 'video-thumbnail'
    = link_to link.title, video_path(:title => link.slug), :class => 'text-center link-title'

app/views/videos/show.html.haml
%main
  .container
    %section.section.row.single_video
      %div{class: @sidebar_videos ? 'col-lg-9' : 'col-lg-12'}
        %h2=@video.title
        .col-lg-6
          =link_to image_tag(video_thumbnail_path(:title => @video.slug, :section => 'video'), :class => 'lg-thumbnail', :alt => @video.title), @video.href, :class => 'video-thumbnail'
        .col-lg-5
          %p= @video.description
        - if @video.subtitle
          .col-lg-12.transcription
            %h3 Transcription
            %p=to_paragraphs @video.subtitle, 6
      - if @sidebar_videos
        .col-lg-3.sidebar
          = render :partial => 'sidebar'

app/views/viewhandler/_big_landscape.html.haml
-section.links.each do |link|
  .clearfix.item.col-lg-10
    .col-md-5.pull-left
      - if link.image
        =link_to image_tag(link.image, :class => 'lg-thumbnail'), link.href, :target => '_blank'
    .col-md-7.col-sm-8.col-xs-12.pull-left
      %h4.text-capitalize
        =link_to link.title, link.href, :target => '_blank'
      %p=link.description

app/views/viewhandler/_big_video.html.haml
-section.links.each do |link|
  .clearfix.item.col-lg-10
    .col-md-5.pull-left
      =link_to image_tag(video_thumbnail_path(:title => link.slug, :section => section.slug), :class => 'lg-thumbnail', :alt => link.title), link.href, :class => 'video-thumbnail', :target => '_blank'
    .col-md-7.col-sm-8.col-xs-12.pull-left
      %h4.text-capitalize
        =link_to link.title, link.href, :target => '_blank'
      %p=link.description

app/views/viewhandler/_big_video_slideshow.html.haml
.cycle-slideshow{ :data => {:cycle_slides => "> div", :cycle_paused => 'true', :cycle_next => '> .pagination > li > .cycle-next', :cycle_prev => '> .pagination > li > .cycle-prev'}}
  - section.links.each_slice(3) do |slide|
    .slide.clearfix
      - slide.each do |link|
        .clearfix.item.col-lg-10
          .col-md-5.pull-left
            =link_to image_tag(video_thumbnail_path(:title => link.slug, :section => section.slug), :class => 'lg-thumbnail', :alt => link.title), link.href, :class => 'video-thumbnail', :target => '_blank'
          .col-md-7.col-sm-8.col-xs-12.pull-left
            %h4.text-capitalize
              =link_to link.title, link.href, :target => '_blank'
            %p=link.description
  - if section.links.count > 3
    %ul.pagination.text-center
      %li
        %a.cycle-prev{:href => "#"} « Prev
      %li
        %a.cycle-next{:href => "#"} » Next       

app/views/viewhandler/_landscape.html.haml
-section.links.each do |link|
  .clearfix.item.col-lg-10
    .col-md-11.col-sm-11.col-xs-12.pull-left
      %h4.text-capitalize
        =link_to link.title, link.href, :target => '_blank'
      %p=link.description

app/views/viewhandler/_portrait.html.haml
- section.links.each do |link|
  .item.col-md-3.col-xs-15.col-sm-6
    .content-box.box-default.text-center
      - if link.image
        =link_to image_tag(link.image, :class => "img-circle", :size => "200x200"), link.href, :class => "text-center"
      - else
        =link_to image_tag("https://placehold.it/200x200", :class => "img-circle"), link.href, :class => "text-center" 
      %h4.content-box-title 
        =link_to link.title, link.href, :target => '_blank'
      %p=link.description

app/views/viewhandler/_three_across_video.html.haml
- section.links.each do |link|
  .item.col-md-4.col-xs-15.col-sm-6
    .content-box.box-default.text-center
      =link_to image_tag(video_thumbnail_path(:title => link.slug, :section => section.slug), :class => 'lg-thumbnail', :alt => link.title), video_path(:title => link.slug ), :class => 'video-thumbnail'
      %h4.content-box-title 
        =link_to link.title, video_path(:title => link.slug)

app/views/viewhandler/_three_across_video_slideshow.html.haml
.cycle-slideshow{ :data => {:cycle_slides => "> div", :cycle_paused => 'true', :cycle_next => '> .pagination > li > .cycle-next', :cycle_prev => '> .pagination > li > .cycle-prev'}}
  - section.links.each_slice(6) do |slide|
    .slide.clearfix
      - slide.each do |link|
        .item.col-md-4.col-xs-15.col-sm-6
          .content-box.box-default.text-center
            =link_to image_tag(video_thumbnail_path(:title => link.slug, :section => section.slug), :class => 'lg-thumbnail', :alt => link.title), video_path(:title => link.slug ), :class => 'video-thumbnail'
            %h4.content-box-title 
              =link_to link.title, video_path(:title => link.slug)
  - if section.links.count > 6
    %ul.pagination.text-center
      %li
        %a.cycle-prev{:href => "#"} « Prev
      %li
        %a.cycle-next{:href => "#"} » Next

app/views/viewhandler/index.html.haml
%main
  .container
    .jumbotron.hero-spacer.visible-sm.visible-xs
      %p=t('tagline').html_safe
    - @sections.each do |section|
      - unless section.links.nil?
        %section{ :id => section.slug, :class => "row section #{section.format}"}
          .col-lg-12
            %h2=section.title
            %p.desc=section.description
            - if section.links
              =render :partial => section.format, :locals => { :section => section }
        %hr/
    - end if @sections
    -#
      %section#blog.row.section
        .col-lg-12
          %h2 Blog
          %p Suspendisse lectus leo, consectetur in tempor sit amet, placerat quis neque. Etiam luctus porttitor lorem, sed suscipit est rutrum non. Curabitur lobortis nisl a enim congue semper. Aenean commodo ultrices imperdiet. Vestibulum ut justo vel sapien venenatis tincidunt. Phasellus eget dolor sit amet ipsum dapibus condimentum vitae quis lectus. Aliquam ut massa in turpis dapibus convallis. Praesent elit lacus, vestibulum at malesuada et, ornare et est. Ut augue nunc, sodales ut euismod non, adipiscing vitae orci. Mauris ut placerat justo. Mauris in ultricies enim. Quisque nec est eleifend nulla ultrices egestas quis ut quam. Donec sollicitudin lectus a mauris pulvinar id aliquam urna cursus. Cras quis ligula sem, vel elementum mi. Phasellus non ullamcorper urna.